### ISSUE TITLE
Delete all files ending in .txt

### ISSUE THREAD

**Issue by Animatnetic** [6outtaTen/kivy_libs#1]
Not necessarily an issue but if you delete all the text files, you can save a bit of storage. Not much, but just a bit.

**Comment by 6outtaTen** [comment]
@Animatnetic Thanks for bringing that into my attention! I will make sure to update it as soon as I can (probably tomorrow).

**Comment by 6outtaTen** [comment]
Done!

**Comment by Animatnetic** [comment]
Cool, ty bro, I did not even realize I pulled an issue/comment
